language: python
python:
  - "2.7"
  - "3.3"

sudo: required

before_install:
- echo $TRAVIS_BUILD_DIR
- echo $pwd

- git clone https://github.com/JeffreyMFarley/hew.git ${HOME}/JeffreyMFarley/hew
- cd ${HOME}/JeffreyMFarley/hew
- python setup.py install
- cd ${TRAVIS_BUILD_DIR}/JeffreyMFarley/pyTagger

install:
- pip install -r requirements.txt

# command to run tests
script: python setup.py test
